module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-bootstrap5
      mounts:
        - source: ../../assets
          target: assets
        - source: ../../layouts
          target: layouts
        - source: ../../static
          target: static
