name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin ${{ github.ref_name }}
          git checkout ${{ github.ref_name }}

      - name: Install Hugo
        run: |
          curl -sL https://github.com/gohugoio/hugo/releases/download/v0.161.1/hugo_extended_0.161.1_linux-amd64.tar.gz | tar xz
          mv hugo /usr/local/bin/hugo

      - name: Build
        run: hugo --gc --minify --baseURL "https://fathrose.github.io/research-group-site/"

      - name: Deploy
        run: |
          cd public
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Deploy"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin HEAD:gh-pages